# Generated by Django 3.2.8 on 2022-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signupdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('password1', models.CharField(max_length=1000)),
                ('password2', models.CharField(max_length=1000)),
            ],
        ),
    ]
